### ISSUE TITLE
Requests

### ISSUE THREAD

**Issue by snandaca** [katalon-studio-samples/ci-samples#7] opened 2018-06-19 20:27 UTC
Hello,
  I am trying to integrate Katalon Docker into CircleCI which is our default CI env.  Travis.io works the same way and I am guessing other online CI envs work the same way, so this should be helpful to you for integrating Katalon with online CI envs.  
 I am able to pull in the latest docker, unfortunately, it is actually putting me in the docker env instead of starting the docker command.  So, I had a couple of requests:
1.  Can you share the actual script / command which you are launching inside the docker?  I need to call it directly once I have downloaded the Katalon docker version and am inside the docker image.
2.  Can you start versioning the images?  I need at least one stable version so my tests don't fail if you accidentally push out an invalid image.
3.  Nice to have - Make the Katalon directory from where it picks up the test files configurable - Currently it looks like this is hard coded to "/katalon/katalon/source".  Can we pass this an option on the command line?
4. Nice to have - Make the reports directory configurable - Currently it looks like it hardcoded to "/katalon/katalon/reports"  

Thanks,
  Nanda

**Comment by devalex88** [comment] 2018-11-21 02:13
Duplicate of katalon-studio/docker-images#16.

**Closed by devalex88** 2018-11-21 02:13 UTC
